<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>

    jQuery.readyException = function( error ) {
        console.error( error );
    };
    // 当包裹在jQuery()或jQuery( document ).ready()，或等效的函数中的函数同步抛出错误的时候，这个方法就会被触发。
    // 默认情况下，在一个超时，它重新抛出错误，因此它被记录在控制台中，并传递给window.onerror，
    // 而不是被静悄悄的吞噬。如果你想以不同的方式处理这种错误，可以覆盖此方法。
</script>
</body>
</html>
